<def f='include/llvm-7/llvm/Support/Error.h' l='546' ll='551' type='llvm::Error llvm::Expected::takeError()'/>
<doc f='include/llvm-7/llvm/Support/Error.h' l='542'>/// Take ownership of the stored error.
  /// After calling this the Expected&lt;T&gt; is in an indeterminate state that can
  /// only be safely destructed. No further calls (beside the destructor) should
  /// be made on the Expected&lt;T&gt; vaule.</doc>
